# Generated by Django 3.2.4 on 2021-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('roomTemp', models.FloatField(max_length=10, null=True)),
                ('roomHumid', models.FloatField(max_length=10, null=True)),
                ('loomHumid', models.FloatField(max_length=10, null=True)),
                ('loomtemp', models.FloatField(max_length=10, null=True)),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
    ]
