# Generated by Django 3.2.4 on 2021-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_sensordata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
