# Generated by Django 3.2.4 on 2021-11-29 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0005_basicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicIOs',
            new_name='BasicIO',
        ),
    ]
